### ISSUE TITLE
API Design improvements

### ISSUE THREAD

**Issue by akorchyn** [near/near-api-rs#19]
This is an epic to address [user feedback](https://docs.google.com/document/d/1M9hNmHyiGRbP7WHtjlZxGkQq3wuUibeqBnIQ6t6Cv6A/edit?tab=t.0)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-api-rs/issues/20
- [ ] https://github.com/near/near-api-rs/issues/21
- [x] Support backup RPC #28
- [x] `sign_message` function specifically for authenticating users as does [wallet-selector](https://docs.near.org/build/web3-apps/backend/#2-ask-the-user-to-sign-the-challenge )
- [x] Remove `prelude` and make docs more readable ([source](https://github.com/near/near-api-rs/pull/16#issuecomment-2514546978)) #29
```
