### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by akorchyn** [near/near-api-rs#25]
We should add useful documentation for the crate with examples. 

```[tasklist]
### Tasks
- [x] Top level documentation (lib.rs)
- [x] All the builders and their methods
- [x] Documentation for structs Contract, Account, Chain, Tokens, Staking, StorageDeposit)
- [x] Signer documentation
- [ ] Type documentation
```
